create table concert (capacity integer not null,price integer not null,reserved_count integer not null,id bigint generated by default as identity,concert_date varchar(255) not null, title varchar(255) not null, primary key (id))
create table ongoing (created_at timestamp(6),id bigint generated by default as identity,user_id bigint,status varchar(255) not null,primary key (id))
create table payment (created_at timestamp(6),payment_id bigint generated by default as identity,user_id bigint not null,reservation_number varchar(255) not null,primary key (payment_id))
create table reservation (seat_num integer not null,created_at timestamp(6),reservation_id bigint generated by default as identity,user_id bigint not null,final_confirm varchar(255) not null,reservation_date varchar(255) not null,reservation_number varchar(255) not null unique,title varchar(255) not null,primary key (reservation_id))
create table users (point integer not null,user_id bigint generated by default as identity,primary key (user_id))
create table waiting (created_at timestamp(6),id bigint generated by default as identity,user_id bigint,status varchar(255) not null,primary key (id)

INSERT INTO concert (title,capacity,reserved_count,price,concert_date) VALUES('PsyConcert',50,50,50000,'20240503');
INSERT INTO concert (title,capacity,reserved_count,price,concert_date) VALUES('PsyConcert',50,0,50000,'20240504');
INSERT INTO concert (title,capacity,reserved_count,price,concert_date) VALUES('OasisConcert',50,50,50000,'20240603');
INSERT INTO concert (title,capacity,reserved_count,price,concert_date) VALUES('OasisConcert',50,45,50000,'20240612');
INSERT INTO concert (title,capacity,reserved_count,price,concert_date) VALUES('MuseConcert',50,23,70000,'20241112');

INSERT INTO reservation (reservation_number,reservation_date,title,seat_num,user_id,final_confirm) VALUES('2024111254','20241112','MuseConcert',4,1,'Y');
INSERT INTO reservation (reservation_number,reservation_date,title,seat_num,user_id,final_confirm) VALUES('2024111251','20241112','MuseConcert',1,2,'Y');
INSERT INTO reservation (reservation_number,reservation_date,title,seat_num,user_id,final_confirm) VALUES('2024111257','20241112','MuseConcert',7,3,'Y');
INSERT INTO reservation (reservation_number,reservation_date,title,seat_num,user_id,final_confirm) VALUES('2024111259','20241112','MuseConcert',9,1,'N');

INSERT INTO users (point) VALUES(100000);
INSERT INTO users (point) VALUES(70000);
INSERT INTO users (point) VALUES(80000);
INSERT INTO users (point) VALUES(2);
